[package]
name = "raxis-core"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61.3", features = [
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
] }
windows-numerics = "0.2.0"
windows-core = "0.61.2"
